---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: cert-manager-client-issuer
  namespace: flux-system
spec:
  dependsOn:
    - name: cert-manager
  path: ./infrastructure/cert-manager/cluster-issuer
  prune: true
  validation: client
